{% set name = "multidoc" %}
{% set version = "0.6.2" %}
{% set build = "1" %}
{% set git_rev = "ea28250c7e702001d920e3512fa1f65b700841a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/geoffreygarrett/multidoc.git
#  - path: ../../../Repositories/multidoc
    git_rev: {{ git_rev }}

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    # Packages that need to be specific to the target platform when the
    # target platform is not necessarily the same as the native build
    # platform
    - python>=3.6
    - pip

  run:
    # Packages required to run the package. These are the dependencies
    # that are installed automatically whenever the package is installed.
    # Package names should follow the package match specifications.
    - pydantic
    - jinja2
    - {{ pin_compatible('pyyaml') }}
    - python>=3.6

test:
  imports:
    - multidoc

  requires:
    - pytest
  source_files:
    - tests/test_generate.py
    - tests/test_parsing.py
    - tests/test_project.py
    - tests/test_template.py

#  commands:
#    - python -c "from tudatpy.kernel.io import get_resource_path; print(get_resource_path())"
#    #- python -c "from tudatpy.apps.satellite_propagator import single; single()"
#    - python -m pytest -v tests/test_constants.py
#    - python -m pytest -v tests/test_io.py


about:
  home: https://multidoc.readthedocs.io/
  license: MIT
  license_family: MIT
  summary: |
    A Python library that automates C++/Pybind11/Python docstring generation
    from a single source.

extra:
  recipe-maintainers:
    - geoffreygarrett
